### ISSUE TITLE
Configure link in a tool window does not work

### ISSUE THREAD

**Issue by jk1** [jk1/youtrack-idea-plugin#108]
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/tasks/TaskManager.getManager must not be null
	at com.intellij.tasks.TaskManager.$$$reportNull$$$0(TaskManager.java)
	at com.intellij.tasks.TaskManager.getManager(TaskManager.java)
	at com.intellij.tasks.config.TaskRepositoriesConfigurable.<init>(TaskRepositoriesConfigurable.java:73)
	at com.intellij.tasks.actions.ConfigureServersAction.actionPerformed(ConfigureServersAction.java:18)
	at com.github.jk1.ytplugin.HelpersKt.runAction(Helpers.kt:18)
	at com.github.jk1.ytplugin.issues.IssuesToolWindowFactory$createPlaceholderPanel$configureLabel$1.invoke(IssuesToolWindowFactory.kt:94)
	at com.github.jk1.ytplugin.issues.IssuesToolWindowFactory$createPlaceholderPanel$configureLabel$1.invoke(IssuesToolWindowFactory.kt:35)
	at com.github.jk1.ytplugin.issues.IssuesToolWindowFactory$createLink$1.mouseClicked(IssuesToolWindowFactory.kt:109)
	at java.awt.Component.processMouseEvent(Component.java:6553)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:692)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jk1** [comment]
Fixed in 0.12
