### ISSUE TITLE
Auto submitted exception from Intellij

### ISSUE THREAD

**Issue by jk1** [jk1/youtrack-idea-plugin#139]
com.intellij.diagnostic.PluginException: com.github.jk1.ytplugin.commands.OpenCommandWindowAction (com.github.jk1.ytplugin.commands.OpenCommandWindowAction): group with id "tasks.toolbar.group" isn't registered; action will be added to the "Other" group [Plugin: com.github.jk1.ytplugin]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:415)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:410)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getParentGroup(ActionManagerImpl.java:930)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processAddToGroupNode(ActionManagerImpl.java:896)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:667)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionsChildElement(ActionManagerImpl.java:1129)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:528)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:171)

**Comment by jk1** [comment]
One require IDEA 2020.3 EAP to reproduce the issue
