### ISSUE TITLE
BindException thrown when open a new IDEA window

### ISSUE THREAD

**Issue by dimarassin** [jk1/youtrack-idea-plugin#14]
Since the plugin requires local port, the following exception is being thrown when open another IDEA (like another project in a new window):

`com.github.jk1.ytplugin.navigator.components.SourceNavigatorComponent@3fb9dd78: Address already in use
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.bind(ServerSocket.java:329)
	at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1687)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by jk1** [comment]
Thank you for reporting it. 

While bugfix release is on it's way I'd appreciate you to try the fix to check if it addresses the problem in your particular environment: https://www.dropbox.com/s/vuef7qvbkrszllo/ytplugin-0.2.1.zip?dl=0 Thanks in advance.

**Comment by jk1** [comment]
The fix has been release in scope of 0.2.1 bugfix update.
