### ISSUE TITLE
Integration of PyCharm 2020.2.3 Pro with Youtrack is broken. Cannot load issues.

### ISSUE THREAD

**Issue by wellic** [jk1/youtrack-idea-plugin#145]
Hi.

I can't load issues from server. The plugin writes 'Are you offline'. I created new token. 
I tried to use recomandations from https://github.com/jk1/youtrack-idea-plugin/issues/143 but no result.

I found in the log of plugin error:
```
2020-10-15 18:41:29,626 [2526699]   INFO -        com.github.jk1.ytplugin - YouTrack issues refresh failed: root.getAsJsonArray("customFields") must not be null
2020-10-15 18:41:29,626 [2526699]  DEBUG -        com.github.jk1.ytplugin -
java.lang.IllegalStateException: root.getAsJsonArray("customFields") must not be null
        at com.github.jk1.ytplugin.issues.model.Issue.<init>(Issue.kt:43)
        at com.github.jk1.ytplugin.rest.IssueParser.parseIssue(IssueParser.kt:9)
        at com.github.jk1.ytplugin.rest.IssuesRestClient$getIssues$issues$1.invoke(IssuesRestClient.kt:92)
        at com.github.jk1.ytplugin.rest.IssuesRestClient$getIssues$issues$1.invoke(IssuesRestClient.kt:20)
        at com.github.jk1.ytplugin.rest.RestClientTrait$DefaultImpls.connect(RestClientTrait.kt:36)
        at com.github.jk1.ytplugin.rest.IssuesRestClient.connect(IssuesRestClient.kt:20)
        at com.github.jk1.ytplugin.rest.IssuesRestClient.getIssues(IssuesRestClient.kt:88)
        at com.github.jk1.ytplugin.issues.IssueStore$RefreshIssuesTask.run(IssueStore.kt:40)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
        at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
        at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
I also tried reinstall plugin, recreated token an so on.

YouTrack Version 2018.3.47109.

Could you help me how to setup plugin.
Thank you.

**Comment by wellic** [comment]
@lesslyrics 
Thank you. I\ve check last veriosn 1.0.5 
My issue is absent. You can close this issue.

**Comment by lesslyrics** [comment]
@wellic thank you for the update.
