### ISSUE TITLE
Cannot fetch issues - Unauthorized

### ISSUE THREAD

**Issue by mmielko** [jk1/youtrack-idea-plugin#151]
Hi,

I am successfully logged in to the youtrack by entering URL and permanent token (scope youtrack) however plugin cannot fetch issues due to unauthorized exception. Testing connection is returning success status. Could you help me

020-11-07 10:00:23,781 [ 707948]   INFO -        com.github.jk1.ytplugin - YouTrack repository https://********.myjetbrains.com/youtrack connected 
2020-11-07 10:00:27,400 [ 711567]  ERROR -        com.github.jk1.ytplugin - Failed to fetch issues for query Assignee: me project: EasYachting-backend-boats  #Unresolved, issues: {}: {"error":"Unauthorized","error_description":""} 
java.lang.Throwable: Failed to fetch issues for query Assignee: me project: ***  #Unresolved, issues: {}: {"error":"Unauthorized","error_description":""}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.github.jk1.ytplugin.rest.IssuesRestClient$getIssues$issues$1.invoke(IssuesRestClient.kt:107)
	at com.github.jk1.ytplugin.rest.IssuesRestClient$getIssues$issues$1.invoke(IssuesRestClient.kt:21)
	at com.github.jk1.ytplugin.rest.RestClientTrait$DefaultImpls.connect(RestClientTrait.kt:36)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.connect(IssuesRestClient.kt:21)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.getIssues(IssuesRestClient.kt:100)
	at com.github.jk1.ytplugin.issues.IssueStore$RefreshIssuesTask.run(IssueStore.kt:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-07 10:00:27,402 [ 711569]  ERROR -        com.github.jk1.ytplugin - IntelliJ IDEA 2020.2.3  Build #IU-202.7660.26 
2020-11-07 10:00:27,402 [ 711569]  ERROR -        com.github.jk1.ytplugin - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-11-07 10:00:27,402 [ 711569]  ERROR -        com.github.jk1.ytplugin - OS: Mac OS X 
2020-11-07 10:00:27,402 [ 711569]  ERROR -        com.github.jk1.ytplugin - Plugin to blame: YouTrack Integration version: 1.0.5 
2020-11-07 10:00:27,402 [ 711569]   INFO -        com.github.jk1.ytplugin - YouTrack issues refresh failed: {"error":"Unauthorized","error_description":""} 
2020-11-07 10:00:27,930 [ 712097]   WARN -        com.github.jk1.ytplugin - Failed to fetch notifications from YouTrack server: {"error":"Unauthorized","error_description":""}

**Comment by jk1** [comment]
Hi,

Thank you for submitting this.
I believe this to be an issue with YouTrack itself: https://youtrack.jetbrains.com/issue/JT-60883. There's already a fix released, so it should be a matter of updating the server.
