### ISSUE TITLE
Unable to show YT issues

### ISSUE THREAD

**Issue by mi6th** [jk1/youtrack-idea-plugin#154]
The YouTrack tab only shows "Nothing to show"

![image](https://user-images.githubusercontent.com/4584067/103444177-f326ae00-4c5d-11eb-88fc-c1727c5646c5.png)

The token for YT server is OK: 

![image](https://user-images.githubusercontent.com/4584067/103444226-9972b380-4c5e-11eb-9035-21e2dc264dbb.png)

---

**YouTrack Integration:** 1.1.0

**PhpStorm 2020.3.1**
Build #PS-203.6682.180, built on December 30, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.85-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1466M
Cores: 4

**Comment by jk1** [comment]
I suppose something may have gone wrong during the plugin init.
May I ask you to attach the IDE log?

**Comment by mi6th** [comment]
1. Error.log is empty
1. [idea.log](https://github.com/jk1/youtrack-idea-plugin/files/5759366/idea.log)
1. [idea_updater.log](https://github.com/jk1/youtrack-idea-plugin/files/5759367/idea_updater.log)

**Comment by jk1** [comment]
Thank you, it helps a lot.

First of all, we do have a notification group registration issue here, similar to #90. 

```
2021-01-01 17:24:51,624 [3066534]   INFO - notification.NotificationGroup - Notification group Time tracking notifications is already registered
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:57)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:25)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:44)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:44)
	at com.github.jk1.ytplugin.timeTracker.TrackerNotification.<init>(TrackerNotification.kt:18)
	at com.github.jk1.ytplugin.timeTracker.actions.StopTrackerAction.stopTimer(StopTrackerAction.kt:43)
	at com.github.jk1.ytplugin.timeTracker.VcsCommitsHandler$createHandler$1.checkinSuccessful(VcsCommitsHandler.kt:23)
	at com.intellij.vcs.commit.CommitHandlersNotifier.onSuccess(CommitHandlersNotifier.kt:13)
	at com.intellij.vcs.commit.AbstractCommitter.finishCommit(AbstractCommitter.kt:155)
	at com.intellij.vcs.commit.AbstractCommitter.doRunCommit(AbstractCommitter.kt:135)
	at com.intellij.vcs.commit.AbstractCommitter.access$doRunCommit(AbstractCommitter.kt:22)
	at com.intellij.vcs.commit.AbstractCommitter$delegateCommitToVcsThread$1$1.run(AbstractCommitter.kt:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.vcs.commit.AbstractCommitter$delegateCommitToVcsThread$1.run(AbstractCommitter.kt:100)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$MyLoggingRunnable.run(ChangeListManagerImpl.java:1675)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

next, a version parsing problem

```
2021-01-01 20:21:24,996 [  59063]  ERROR - llij.ide.plugins.PluginManager - multiple points
java.lang.NumberFormatException: multiple points
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at com.github.jk1.ytplugin.ui.IssueSearchBar.<init>(IssueSearchBar.kt:47)
	at com.github.jk1.ytplugin.ui.IssueListToolWindowContent.<init>(IssueListToolWindowContent.kt:24)
	at com.github.jk1.ytplugin.issues.IssuesToolWindowFactory.createContent(IssuesToolWindowFactory.kt:76)
	at com.github.jk1.ytplugin.issues.IssuesToolWindowFactory.createToolWindowContent(IssuesToolWindowFactory.kt:43)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:506)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:486)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:980)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:926)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:632)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$default(ToolWindowManagerImpl.kt:613)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1838)
	at com.intellij.openapi.wm.impl.StripeButton.lambda$new$0(StripeButton.java:65)
```

Finally, something went wrong with a text custom field parser

```
YouTrack issue parse error. Offending element: {"projectCustomField":{"emptyFieldText":"...","$type":"TextProjectCustomField"},"value":{"$type":"TextFieldValue"},"name":"...","id":"129-6","$type":"TextIssueCustomField"}
```

**Comment by sergyu91ma** [comment]
i have same problem on version 1.1.1

**Comment by mi6th** [comment]
@sergyu91ma I can confirm it's still broken

**Comment by sergyu91ma** [comment]
@mi6th Then this issue should be reopened, i guess.

**Comment by mi6th** [comment]
@sergyu91ma Indeed but I can't reopen it. I'm just a reporter and the issue is assigned to @jk1

**Comment by jk1** [comment]
@mi6th @sergyu91ma would you mind trying 1.1.2 instead?
I'm terribly sorry for the confusion.

**Comment by mi6th** [comment]
Bravo @jk1 It works now 😃

**Comment by jk1** [comment]
That's great to hear.
Thank you for the confirmation.

**Comment by sergyu91ma** [comment]
Works for me too. Nice
