### ISSUE TITLE
Youtrack plugin not working after the update

### ISSUE THREAD

**Issue by mknithin** [jk1/youtrack-idea-plugin#160]
I'm using youtrack plugin with Pycharm, and after the last update to version 1.1.3 it's not working. The configure button triggers nothing.
Don't know the problem is only with my instance. Please advice a fix to this.

<img width="1623" alt="Screen Shot 2021-02-14 at 10 26 20 AM" src="https://user-images.githubusercontent.com/15276904/107870087-1d02ff80-6eaf-11eb-9fd5-e56d9c6b87a1.png">

**Comment by jk1** [comment]
Hi there. Attaching an IDE log would help a lot.

**Comment by mknithin** [comment]
Sure! , here you have the logs attached. Thanks
[idea.log](https://github.com/jk1/youtrack-idea-plugin/files/5977099/idea.log)

**Comment by jk1** [comment]
Thanks, it helps a lot.

```
java.lang.IllegalArgumentException: host parameter is null
	at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:206)
	at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:155)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionWithReference.<init>(MultiThreadedHttpConnectionManager.java:1145)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ConnectionPool.createConnection(MultiThreadedHttpConnectionManager.java:762)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.doGetConnection(MultiThreadedHttpConnectionManager.java:476)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.getConnectionWithTimeout(MultiThreadedHttpConnectionManager.java:416)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:153)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.github.jk1.ytplugin.rest.TimeTrackerRestClient$getAvailableWorkItemTypes$1.invoke(TimeTrackerRestClient.kt:93)
	at com.github.jk1.ytplugin.rest.TimeTrackerRestClient$getAvailableWorkItemTypes$1.invoke(TimeTrackerRestClient.kt:21)
	at com.github.jk1.ytplugin.rest.RestClientTrait$DefaultImpls.connect(RestClientTrait.kt:35)
	at com.github.jk1.ytplugin.rest.TimeTrackerRestClient.connect(TimeTrackerRestClient.kt:21)
	at com.github.jk1.ytplugin.rest.TimeTrackerRestClient.getAvailableWorkItemTypes(TimeTrackerRestClient.kt:91)
	at com.github.jk1.ytplugin.timeTracker.TimeTrackingService.getAvailableWorkItemsTypes(TimeTrackingService.kt:20)
	at com.github.jk1.ytplugin.timeTracker.TimeTrackerSettingsTab.createTypePanel(TimeTrackerSettingsTab.kt:121)
	at com.github.jk1.ytplugin.timeTracker.TimeTrackerSettingsTab.<init>(TimeTrackerSettingsTab.kt:65)
	at com.github.jk1.ytplugin.setup.SetupDialog.<init>(SetupDialog.kt:58)
	at com.github.jk1.ytplugin.issues.IssuesToolWindowFactory$createPlaceholderPanel$configureLabel$1.invoke(IssuesToolWindowFactory.kt:100)
	at com.github.jk1.ytplugin.issues.IssuesToolWindowFactory$createPlaceholderPanel$configureLabel$1.invoke(IssuesToolWindowFactory.kt:37)
	at com.github.jk1.ytplugin.issues.IssuesToolWindowFactory$createLink$1.mouseClicked(IssuesToolWindowFactory.kt:115)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
