### ISSUE TITLE
Intellij Ultimate Edition doesn't run at all

### ISSUE THREAD

**Issue by anastasiya315510** [jk1/youtrack-idea-plugin#169]
Intellij Ultimate Edition doesn't run at all. When Intellij   starts after restarting computer, its downloaded the list of projects, but you cant choose anything... the window suddenly dissappeared. And after that, you can't start Intellij Ultimate Edition at all.(I have also free Intellij Edu and it's working well).
I thought that it was a memory issue, but the command "ulimit -H -c unlimited" does'nt help
 What should I do?

here is the log:
2021-04-09 23:01:53,300 [  84342]  ERROR - llij.ide.plugins.PluginManager - Sorry but parent: {DBNavigator.ProjectRef=com.dci.intellij.dbn.common.project.ProjectRef@4e50cbe6, com.jetbrains.rd.platform.util.lifetime=com.jetbrains.rd.util.lifetime.LifetimeDefinition@46b3cb8} has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.project.impl.DefaultProject$1@2239aa65 will never be disposed 
com.intellij.util.IncorrectOperationException: Sorry but parent: {DBNavigator.ProjectRef=com.dci.intellij.dbn.common.project.ProjectRef@4e50cbe6, com.jetbrains.rd.platform.util.lifetime=com.jetbrains.rd.util.lifetime.LifetimeDefinition@46b3cb8} has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.project.impl.DefaultProject$1@2239aa65 will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:55)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:73)
	at com.intellij.openapi.project.impl.DefaultProject$1.compute(DefaultProject.java:46)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:31)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:130)
	at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.java:234)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:204)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.getProject(FlatWelcomeFrame.java:530)
	at com.jetbrains.rdserver.ui.popup.bePopups.impl.BackendBePopupFactory.tryGuessFocusedProject(BackendBePopupFactory.kt:51)
	at com.jetbrains.rdserver.ui.popup.bePopups.impl.BackendBePopupFactory.createComponentPopupBuilder(BackendBePopupFactory.kt:123)
	at com.intellij.ide.HelpTooltip.initPopupBuilder(HelpTooltip.java:340)
	at com.intellij.ide.HelpTooltip.initPopupBuilder(HelpTooltip.java:346)
	at com.intellij.ide.HelpTooltipManager.showTooltip(HelpTooltipManager.java:21)
	at com.intellij.ide.IdeTooltipManager.showTooltipForEvent(IdeTooltipManager.java:264)
	at com.intellij.ide.IdeTooltipManager.showForComponent(IdeTooltipManager.java:244)
	at com.intellij.ide.IdeTooltipManager.maybeShowFor(IdeTooltipManager.java:203)
	at com.intellij.ide.IdeTooltipManager.eventDispatched(IdeTooltipManager.java:126)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2199)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2091)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2047)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4933)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4698)
	at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4676)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4527)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by anastasiya315510** [comment]
the video how it's working in this link https://drive.google.com/file/d/1hWTc9sI57IuGudHrUtxblJReK1pyEApe/view?usp=sharing

**Comment by jk1** [comment]
Hi @anastasiya315510,

Thank you for getting in touch. Neither the stack trace nor the video suggest that the issue is related to YouTrack plugin.
If it's a generic Intellij Ultimate issue, then it's better be reported to https://youtrack.jetbrains.com/newIssue?project=IDEA.

You may also consider taking a closer look at https://youtrack.jetbrains.com/issue/IDEA-266010, which looks quite similar to the problem you're facing.
