### ISSUE TITLE
YouTrack issues refresh failed

### ISSUE THREAD

**Issue by Meharas** [jk1/youtrack-idea-plugin#24]
YouTrack issues refresh failed
java.lang.NullPointerException
	at com.github.jk1.ytplugin.search.model.Issue.<init>(Issue.kt:32)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient$getWikifiedIssuesInProject$1.invoke(IssuesRestClient.kt:40)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient$getWikifiedIssuesInProject$1.invoke(IssuesRestClient.kt:20)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient.execute(IssuesRestClient.kt:50)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient.getWikifiedIssuesInProject(IssuesRestClient.kt:40)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient.getIssues(IssuesRestClient.kt:24)
	at com.github.jk1.ytplugin.search.components.IssueStoreComponent$Store$refresh$1.run(IssueStoreComponent.kt:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jk1** [comment]
@Meharas, would you mind recording and sharing YouTrack server response? To do so 

1. Select 'Debug Log Settings...' in 'Help' menu 
2. Add #com.github.jk1 and #org.apache.commons.httpclient categories to the list
3. Hit refresh button on a plugin tool window
4. Explore idea log file via 'Help' menu, it should contain JSON response from YouTrack server

Thanks in advance.

**Comment by Meharas** [comment]
That's all found in idea.log:

`2016-08-10 07:42:43,598 [2388832]   INFO - agnostic.FrequentEventDetector - Too many events posted, #1. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.util.containers.TransferToEDTQueue$1@e27b75,notifier=null,catchExceptions=false,when=1470807763598] on sun.awt.windows.WToolkit@1706ba7 
2016-08-10 07:42:44,019 [2389253]   INFO - agnostic.FrequentEventDetector - Too many events posted, #1. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.util.containers.TransferToEDTQueue$1@e27b75,notifier=null,catchExceptions=false,when=1470807764019] on sun.awt.windows.WToolkit@1706ba7 
2016-08-10 07:44:12,302 [2477536]   INFO - lij.diagnostic.DebugLogManager - Set TRACE for the following categories: #com.github.jk1, #org.apache.commons.httpclient 
2016-08-10 07:44:14,801 [2480035]  DEBUG - ents.IssueStoreComponent$Store - Issue store refresh started for project xxx and YouTrack server http://youtrack 
2016-08-10 07:44:14,817 [2480051]  DEBUG - StoreComponent$Store$refresh$1 - Fetching issues for search query: sort by: updated  
2016-08-10 07:44:14,879 [2480113]   WARN - mons.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended. 
2016-08-10 07:44:14,879 [2480113]  DEBUG - s.httpclient.methods.GetMethod - {"issue":...} 
2016-08-10 07:44:14,973 [2480207]   WARN - mons.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended. 
2016-08-10 07:44:14,988 [2480222]  DEBUG - s.httpclient.methods.GetMethod - [...] 
2016-08-10 07:44:15,004 [2480238]  ERROR - StoreComponent$Store$refresh$1 - YouTrack issues refresh failed 
java.lang.NullPointerException
	at com.github.jk1.ytplugin.search.model.Issue.<init>(Issue.kt:32)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient$getWikifiedIssuesInProject$1.invoke(IssuesRestClient.kt:40)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient$getWikifiedIssuesInProject$1.invoke(IssuesRestClient.kt:20)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient.execute(IssuesRestClient.kt:50)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient.getWikifiedIssuesInProject(IssuesRestClient.kt:40)
	at com.github.jk1.ytplugin.search.rest.IssuesRestClient.getIssues(IssuesRestClient.kt:24)
	at com.github.jk1.ytplugin.search.components.IssueStoreComponent$Store$refresh$1.run(IssueStoreComponent.kt:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-08-10 07:44:15,004 [2480238]  ERROR - StoreComponent$Store$refresh$1 - IntelliJ IDEA 2016.2.1  Build #IU-162.1447.26 
2016-08-10 07:44:15,004 [2480238]  ERROR - StoreComponent$Store$refresh$1 - JDK: 1.8.0_76-release 
2016-08-10 07:44:15,004 [2480238]  ERROR - StoreComponent$Store$refresh$1 - VM: OpenJDK Server VM 
2016-08-10 07:44:15,004 [2480238]  ERROR - StoreComponent$Store$refresh$1 - Vendor: JetBrains s.r.o 
2016-08-10 07:44:15,004 [2480238]  ERROR - StoreComponent$Store$refresh$1 - OS: Windows 7 
2016-08-10 07:44:15,004 [2480238]  DEBUG - StoreComponent$Store$refresh$1 - Issue store has been updated for YouTrack server http://youtrack `

**Comment by jk1** [comment]
> 2016-08-10 07:44:14,879 [2480113] DEBUG - s.httpclient.methods.GetMethod - {"issue":...} 
> 2016-08-10 07:44:14,988 [2480222] DEBUG - s.httpclient.methods.GetMethod - [...] 

These are the lines I'm after. Please share their full content.

**Comment by jk1** [comment]
Thank you, this explains much. The fix is coming soon.

**Comment by jk1** [comment]
Fixed in 0.3.3
