### ISSUE TITLE
Exception while trying to invoke Command Dialog

### ISSUE THREAD

**Issue by rar91279** [jk1/youtrack-idea-plugin#32]
If i try to invoke a Command Dialog on an active Youtrack Task, an Exception is thrown :

---
2016-09-20 19:42:29,645 [2188955]  DEBUG -        com.github.jk1.ytplugin - <?xml version="1.0" encoding="UTF-8" standalone="yes"?><error>Not Found</error> 
2016-09-20 19:42:29,645 [2188955]  ERROR - llij.ide.plugins.PluginManager - <?xml version="1.0" encoding="UTF-8" standalone="yes"?><error>Not Found</error> 
java.lang.RuntimeException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><error>Not Found</error>
	at com.github.jk1.ytplugin.commands.rest.AdminRestClient.getUserGroups(AdminRestClient.kt:26)
	at com.github.jk1.ytplugin.commands.components.AdminComponentImpl.getUserGroups(AdminComponentImpl.kt:13)
	at com.github.jk1.ytplugin.commands.CommandDialog.<init>(CommandDialog.kt:38)
	at com.github.jk1.ytplugin.commands.OpenCommandWindowAction.actionPerformed(OpenCommandWindowAction.kt:30)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-09-20 19:42:29,646 [2188956]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2016.2.3  Build #IU-162.1812.17 
2016-09-20 19:42:29,646 [2188956]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_112-release 
2016-09-20 19:42:29,646 [2188956]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK Server VM 
2016-09-20 19:42:29,646 [2188956]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2016-09-20 19:42:29,646 [2188956]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2016-09-20 19:42:29,646 [2188956]  ERROR - llij.ide.plugins.PluginManager - Last Action: com.github.jk1.ytplugin.commands.OpenCommandWindowAction 

---
Youtrack Plugin was freshly installed today. 
Youtrack Version: 5.2.5 (selfhosted standalone version)
IntelliJ Idea: 2016.2.3
Search query: "Assignee: me sort by: updated State: Open, Re-open,{ In Progress}"
Authentikation via LDAP (ActiveDirectory)

**Comment by jk1** [comment]
Thank you for reporting it. 
It look like YouTrack 5.2 does not expose eligible visibility groups via rest at all.

**Comment by rar91279** [comment]
Thank you, just verified, works like a charm.
