### ISSUE TITLE
Stacktrace when re-opening project that has youtrack window open

### ISSUE THREAD

**Issue by chmarr** [jk1/youtrack-idea-plugin#52]
If I have the youtrack window open, showing tickets and a ticket detail, then close the project window, and then reopen the same project, PyCharm shows an "IDE Error" related to the youtrack plugin. Here's the stack trace. (the project name has been replaced with "xxxx")

Running plugin version 0.5.2. PyCharm 2016.3.2

```
Already disposed: Project (Disposed) xxxx
java.lang.AssertionError: Already disposed: Project (Disposed) xxxx
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:172)
	at com.github.jk1.ytplugin.ComponentAware$DefaultImpls.getIssueStoreComponent(ComponentAware.kt:34)
	at com.github.jk1.ytplugin.ui.IssueListToolWindowContent.getIssueStoreComponent(IssueListToolWindowContent.kt:29)
	at com.github.jk1.ytplugin.ui.IssueListToolWindowContent$IssueListModel.getSize(IssueListToolWindowContent.kt:139)
	at javax.swing.plaf.basic.BasicListUI.adjustIndex(BasicListUI.java:2828)
	at javax.swing.plaf.basic.BasicListUI.access$200(BasicListUI.java:57)
	at javax.swing.plaf.basic.BasicListUI$Handler.repaintCellFocus(BasicListUI.java:2805)
	at javax.swing.plaf.basic.BasicListUI$Handler.focusLost(BasicListUI.java:2823)
	at javax.swing.plaf.basic.BasicListUI$FocusHandler.focusLost(BasicListUI.java:1577)
	at com.apple.laf.AquaListUI$FocusHandler.focusLost(AquaListUI.java:103)
	at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:230)
	at java.awt.Component.processFocusEvent(Component.java:6425)
	at java.awt.Component.processEvent(Component.java:6289)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:995)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:661)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by chmarr** [comment]
Thank you! 😻 I'll verify once 0.6 is available. Thank you for your efforts!

**Comment by jk1** [comment]
You're always welcome.
I hope it won't take me long to finish 0.6 and release it.

**Comment by chmarr** [comment]
Verified fixed!
