### ISSUE TITLE
Project disposed exception with IJ Ultimate 2017.1

### ISSUE THREAD

**Issue by jk1** [jk1/youtrack-idea-plugin#59]
Sorry but parent: Project (Disposed) youtrack has already been disposed (see the cause for stacktrace) so the child: null 1724598359: running=false; canceled=false will never be disposed
com.intellij.util.IncorrectOperationException: Sorry but parent: Project (Disposed) youtrack has already been disposed (see the cause for stacktrace) so the child: null 1724598359: running=false; canceled=false will never be disposed
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:66)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:95)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:91)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:123)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:82)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:71)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:52)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressAsynchronously(ProgressManagerImpl.java:111)
	at com.intellij.openapi.progress.impl.CoreProgressManager.b(CoreProgressManager.java:347)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:349)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:331)
	at com.intellij.openapi.progress.Task.queue(Task.java:115)
	at com.github.jk1.ytplugin.issues.IssueStore.update(IssueStore.kt:21)
	at com.github.jk1.ytplugin.issues.IssueStoreUpdaterComponent$initComponent$1$1.run(IssueStoreUpdaterComponent.kt:25)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by joerg-bergner** [comment]
+1
