### ISSUE TITLE
Exception in IDEA 2017.1.3. EAP

### ISSUE THREAD

**Issue by jk1** [jk1/youtrack-idea-plugin#62]
update failed for ActionGroup: youtrack (null)[youtrack]
java.lang.NullPointerException
	at com.intellij.ide.favoritesTreeView.PsiFieldFavoriteNodeProvider.getElementUrl(PsiFieldFavoriteNodeProvider.java:117)
	at com.intellij.ide.favoritesTreeView.FavoritesManager.createUrlByElement(FavoritesManager.java:547)
	at com.intellij.ide.favoritesTreeView.FavoritesManager.a(FavoritesManager.java:219)
	at com.intellij.ide.favoritesTreeView.FavoritesManager.canAddRoots(FavoritesManager.java:249)
	at com.intellij.ide.favoritesTreeView.actions.AddToFavoritesAction.canCreateNodes(AddToFavoritesAction.java:123)
	at com.intellij.ide.favoritesTreeView.actions.AddToFavoritesAction.update(AddToFavoritesAction.java:101)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:131)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:234)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:311)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:285)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:251)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:193)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:99)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:340)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.a(ActionMenu.java:326)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:280)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
	at javax.swing.JMenu.setSelected(JMenu.java:305)
	at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1187)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:244)
	at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125)
	at javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:450)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jk1** [comment]
Doesn't seem to happen anymore. May be an IDE bug fixed since then.
