### ISSUE TITLE
Error connection to Jira

### ISSUE THREAD

**Issue by elysrivero99** [jk1/youtrack-idea-plugin#73]
I've created a new connection to jira and when I test the connection, all seem to be fine:

![image](https://user-images.githubusercontent.com/3760276/32000926-82d55c4c-b998-11e7-9693-9168d81a1bb6.png)

But, when I save the connection I see this error:

Credentials cannot be used for NTLM authentication: org.apache.commons.httpclient.UsernamePasswordCredentials
org.apache.commons.httpclient.auth.InvalidCredentialsException: Credentials cannot be used for NTLM authentication: org.apache.commons.httpclient.UsernamePasswordCredentials
	at org.apache.commons.httpclient.auth.NTLMScheme.authenticate(NTLMScheme.java:332)
	at org.apache.commons.httpclient.HttpMethodDirector.authenticateProxy(HttpMethodDirector.java:320)
	at org.apache.commons.httpclient.HttpMethodDirector.executeConnect(HttpMethodDirector.java:491)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:391)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.github.jk1.ytplugin.rest.IssuesRestClient$execute$1.invoke(IssuesRestClient.kt:60)
	at com.github.jk1.ytplugin.rest.IssuesRestClient$execute$1.invoke(IssuesRestClient.kt:14)
	at com.github.jk1.ytplugin.rest.RestClientTrait$DefaultImpls.connect(RestClientTrait.kt:24)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.connect(IssuesRestClient.kt:14)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.execute(IssuesRestClient.kt:59)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.getIssueIds(IssuesRestClient.kt:43)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.getIssues(IssuesRestClient.kt:32)
	at com.github.jk1.ytplugin.issues.IssueStore$RefreshIssuesTask.run(IssueStore.kt:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Plugin Version: 0.7.2

**Comment by jk1** [comment]
Hi, thanks for reporting this.
Have you tried to configure YouTrack connection in this project before?

**Comment by elysrivero99** [comment]
No, I haven't. It was the first time.

**Comment by jk1** [comment]
I see. Let me explain how it all works a bit.

This plugin is all about YouTrack bug tracker integration, it has nothing to do with Jira. It's based on Task Management plugin by Jetbrains though, which provides basic integration with many bug trackers, Jira included. All that said you can uninstall YouTrack plugin and use bare Task Management plugin to integrate with Jira to avoid errors thrown from YouTrack plugin.

**Comment by elysrivero99** [comment]
Ok, I've uninstalled and its works fine. Thx.
