### ISSUE TITLE
NPE from IntelliJ EA

### ISSUE THREAD

**Issue by ignatov** [jk1/youtrack-idea-plugin#77]
annotator: com.github.jk1.ytplugin.commands.lang.CommandHighlightingAnnotator@27183a07 (class com.github.jk1.ytplugin.commands.lang.CommandHighlightingAnnotator)

java.lang.NullPointerException
	at com.github.jk1.ytplugin.commands.model.CommandSuggestion.asStringNullSafe(CommandSuggestion.kt:37)
	at com.github.jk1.ytplugin.commands.model.CommandSuggestion.asStringNullSafe$default(CommandSuggestion.kt:35)
	at com.github.jk1.ytplugin.commands.model.CommandSuggestion.<init>(CommandSuggestion.kt:30)
	at com.github.jk1.ytplugin.commands.model.CommandAssistResponse.<init>(CommandAssistResponse.kt:24)
	at com.github.jk1.ytplugin.rest.CommandRestClient$assistCommand$1.invoke(CommandRestClient.kt:22)
	at com.github.jk1.ytplugin.rest.CommandRestClient$assistCommand$1.invoke(CommandRestClient.kt:13)
	at com.github.jk1.ytplugin.rest.RestClientTrait$DefaultImpls.connect(RestClientTrait.kt:24)
	at com.github.jk1.ytplugin.rest.CommandRestClient.connect(CommandRestClient.kt:13)
	at com.github.jk1.ytplugin.rest.CommandRestClient.assistCommand(CommandRestClient.kt:19)
	at com.github.jk1.ytplugin.commands.CommandComponentImpl.suggest(CommandComponentImpl.kt:46)
	at com.github.jk1.ytplugin.ui.CommandDialog$CommandSuggestListener.suggest(CommandDialog.kt:165)
	at com.github.jk1.ytplugin.commands.lang.CommandHighlightingAnnotator.collectInformation(CommandHighlightingAnnotator.kt:35)
	at com.github.jk1.ytplugin.commands.lang.CommandHighlightingAnnotator.collectInformation(CommandHighlightingAnnotator.kt:21)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1140)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:216)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by jk1** [comment]
@ignatov please elaborate, what idea and plugin version is that?
To the moment it doesn't seem reproducible to me.
