### ISSUE TITLE
Issue refresh failed with an exception

### ISSUE THREAD

**Issue by jk1** [jk1/youtrack-idea-plugin#78]
2018-02-26 15:02:13,995 [14786108]   WARN -        com.github.jk1.ytplugin - YouTrack issue parse error. Offending element: {"name":"markdown","value":"false"} 
2018-02-26 15:02:13,996 [14786109]  DEBUG -        com.github.jk1.ytplugin -  
java.lang.IllegalStateException: Not a JSON Array: "false"
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107)
	at com.github.jk1.ytplugin.issues.model.CustomField.<init>(CustomField.kt:21)
	at com.github.jk1.ytplugin.rest.IssueJsonParser$parseCustomField$1.invoke(IssueJsonParser.kt:11)
	at com.github.jk1.ytplugin.rest.IssueJsonParser$parseCustomField$1.invoke(IssueJsonParser.kt:7)
	at com.github.jk1.ytplugin.rest.IssueJsonParser.parseSafe(IssueJsonParser.kt:23)
	at com.github.jk1.ytplugin.rest.IssueJsonParser.parseCustomField(IssueJsonParser.kt:11)
	at com.github.jk1.ytplugin.issues.model.Issue.<init>(Issue.kt:46)
	at com.github.jk1.ytplugin.rest.IssueJsonParser$parseIssue$1.invoke(IssueJsonParser.kt:9)
	at com.github.jk1.ytplugin.rest.IssueJsonParser$parseIssue$1.invoke(IssueJsonParser.kt:7)
	at com.github.jk1.ytplugin.rest.IssueJsonParser.parseSafe(IssueJsonParser.kt:23)
	at com.github.jk1.ytplugin.rest.IssueJsonParser.parseIssue(IssueJsonParser.kt:9)
	at com.github.jk1.ytplugin.rest.IssuesRestClient$getWikifiedIssuesInProject$1.invoke(IssuesRestClient.kt:53)
	at com.github.jk1.ytplugin.rest.IssuesRestClient$getWikifiedIssuesInProject$1.invoke(IssuesRestClient.kt:14)
	at com.github.jk1.ytplugin.rest.IssuesRestClient$execute$1.invoke(IssuesRestClient.kt:62)
	at com.github.jk1.ytplugin.rest.IssuesRestClient$execute$1.invoke(IssuesRestClient.kt:14)
	at com.github.jk1.ytplugin.rest.RestClientTrait$DefaultImpls.connect(RestClientTrait.kt:24)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.connect(IssuesRestClient.kt:14)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.execute(IssuesRestClient.kt:58)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.getWikifiedIssuesInProject(IssuesRestClient.kt:53)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.getIssues(IssuesRestClient.kt:35)
	at com.github.jk1.ytplugin.issues.IssueStore$RefreshIssuesTask.run(IssueStore.kt:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jk1** [comment]
Fixed in 0.8.1
