### ISSUE TITLE
Cannot connect to youtrack, are you offline?

### ISSUE THREAD

**Issue by TransmissionsDev** [jk1/youtrack-idea-plugin#83]
I keep getting the "Cannot connect to youtrack, are you offline?" even though I am online. Is there a way to fix this issue, I have tried re-installing the plugin, restarting the IDE multiple times, and my computer has been restarted. 

Thanks!

**Comment by jk1** [comment]
Please reproduce the problem with debug log settings (https://github.com/jk1/youtrack-idea-plugin#plugin-logs) and attach IDE log here. Thanks in advance.

**Comment by Piskvor** [comment]
This seems to be a change in login flow inside the YouTrack API - this broke for me at the exact same time as another library interfacing with YouTrack, even though my permissions in YT haven't changed: YouTrack no longer accepts username+password logins, it seems.

```
{"value":"You are not logged in."}
java.lang.RuntimeException: {"value":"You are not logged in."}
	at com.github.jk1.ytplugin.rest.RestClientTrait$execute$1.invoke(RestClientTrait.kt:48)
	at com.github.jk1.ytplugin.rest.RestClientTrait$execute$1.invoke(RestClientTrait.kt:16)
	at com.github.jk1.ytplugin.rest.RestClientTrait$DefaultImpls.connect(RestClientTrait.kt:34)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.connect(IssuesRestClient.kt:10)
	at com.github.jk1.ytplugin.rest.RestClientTrait$DefaultImpls.execute(RestClientTrait.kt:42)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.execute(IssuesRestClient.kt:10)
	at com.github.jk1.ytplugin.rest.IssuesRestClient.getIssue(IssuesRestClient.kt:15)
	at com.github.jk1.ytplugin.commands.OpenCommandWindowAction$getIssueFromCurrentActiveTask$1.invoke(OpenCommandWindowAction.kt:62)
	at com.github.jk1.ytplugin.commands.OpenCommandWindowAction$getIssueFromCurrentActiveTask$1.invoke(OpenCommandWindowAction.kt:22)
	at com.github.jk1.ytplugin.ComponentAware$Companion.of(ComponentAware.kt:24)
	at com.github.jk1.ytplugin.commands.OpenCommandWindowAction.getIssueFromCurrentActiveTask(OpenCommandWindowAction.kt:54)
	at com.github.jk1.ytplugin.commands.OpenCommandWindowAction.actionPerformed(OpenCommandWindowAction.kt:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:357)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.n(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by jk1** [comment]
@Piskvor please share YouTrack version and plugin version used

**Comment by Piskvor** [comment]
@jk1: PhpStorm 2018.1.1
Build #PS-181.4445.72, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-38-generic

Youtrack integration plugin
Version: 0.9.1

Also seeing exact same issue in https://github.com/nepda/youtrack-client (latest), which uses the same YouTrack API.

**Comment by jk1** [comment]
> YouTrack no longer accepts username+password logins, it seems

I've checked that and can confirm this is not the case. 
Are you able to login with the same credentials via browser?

**Comment by Piskvor** [comment]
Aha, that's probably the difference. I checked and my organization only allows browser login via Google Auth - but I'm still allowed to add auth credentials (not tokens).

**Comment by Piskvor** [comment]
Yet for some reason, this used to work. Perhaps *that* was a bug, IDK. Oh well.

Thanks for the support :)
