### ISSUE TITLE
NPE at getAvailableTaskStates

### ISSUE THREAD

**Issue by YoungjaeKim** [jk1/youtrack-idea-plugin#99]
I've changed YouTrack from http to https and it could not get state link. I don't know the relationship between this issue and http/s. Getting issues are fine.

- Plugin version: 0.9.4
- IDE: Android Studio 3.3.2

```stacktrace
java.lang.NullPointerException
	at com.intellij.tasks.youtrack.YouTrackRepository.getAvailableTaskStates(YouTrackRepository.java:221)
	at com.intellij.tasks.impl.TaskStateCombo$1.fetch(TaskStateCombo.java:77)
	at com.intellij.tasks.impl.TaskStateCombo$1.fetch(TaskStateCombo.java:73)
	at com.intellij.tasks.impl.TaskUiUtil$RemoteFetchTask.run(TaskUiUtil.java:53)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jk1** [comment]
@YoungjaeKim what YouTrack version you have installed?

**Comment by YoungjaeKim** [comment]
@jk1 Hi. I'm using YouTrack 2019.1 (Build 51277)

**Comment by jk1** [comment]
So it must be a YouTrack bug then. 
Please refer to #96 for more details on that.
